# focus_to_kanata.py reads this file.

# *************** KWANATA - KANATA configuration ******************

# KWanata injects a script in KDE that gets information about a windows
# whenever there is a change in whe window that its currently active.
# It will check then this cofiguration, to determine how to report to kanata.
# The first app matching is the one whose layer/virtual_keys are send
# to kanata.
#
# Format:

# [[app]]
# name = "name_of_app regex"          # Optional.
# class = "class_of_app regex"        # Optional.
# caption = "title_of_window regex"   # Optional.
# layer = "kanata_layer_name"         # Optional.
# virtual_keys = ["vk1", "vk2", ...]  # Optional.
#
# name, class and caption are used to match the info of the current active 
# window. layer and virtual_keys are sent to kanata if a match is detected.
#
# If more than one field to match is present, they all need to match.

[[app]]
name = "chrome"
virtual_keys = ["vk_chrome"]

[[app]]
name = "obsidian"
virtual_keys = ["vk_obsidian"]

[[app]]
name = "foot"
caption = "^tmux.*(N|n)vim$"
virtual_keys = ["vk_nvim", "vk_tmux"]

[[app]]
name = "foot"
caption = "^tmux"
virtual_keys = ["vk_tmux", "vk_foot"]

[[app]]
name = "foot"
caption = "^Zellij"
virtual_keys = ["vk_zellij", "vk_foot"]

[[app]]
name = "foot"
caption = "(N|n)vim$"
virtual_keys = ["vk_nvim"]

[[app]]
name = "konsole"
caption = "zellij — Konsole$"
virtual_keys = ["vk_zellij"]

[[app]]
name = "konsole"
caption = "nvim — Konsole$"
virtual_keys = ["vk_nvim"]

[[app]]
name = "foot|konsole"
virtual_keys = ["vk_foot"]

[[app]]
name = "dolphin"
virtual_keys = ["vk_dolphin"]

[[app]]
caption = "(All Files|Save File — Skanpage)"
virtual_keys = ["vk_dolphin"]

# *************** KWANATA - Run Or Raise configuration ******************

# Run-or-raise: triggered by Kanata push-msg "APP: <name>"
# [[run_or_raise]] could  have these fields:
# name -- Name of the app (required). 
# class -- App's class (optional). It is a regex. It will be use to search 
#          if the app is running.
# caption -- App's caption (optional). It is a regex. It will be use to 
#            search if the app is running.
# command -- Command to launch the app (if omitted, name will be used as 
#            command). It the app is not running command will run.
# process -- Name of the process to check if the app is running (if omitted,
#            command will be uses as process). It is a regex.
#
# Defaults: class="", caption="", command=name, process=command.
# NOTE: At least caption or class should be defined to reach and app.

# Chrome app - When raised multiple times it will iterate through opened chrome windows.
[[run_or_raise]]
name = "chrome"
class = "google-chrome"
command = "google-chrome-stable"
process = "chrome"

# Chrome app - Mgmt window (It will find a window with an active tab with @Mgmt in its title).
[[run_or_raise]]
name = "chromeMgmt"
class = "google-chrome"
caption = "@Mgmt"
command = "google-chrome-stable"
process = "chrome"

# Chrome app - Cloud window (It will find a window with an active tab with @Cloud in its title).
[[run_or_raise]]
name = "chromeCloud"
class = "google-chrome"
caption = "@Cloud - Google Chrome$"
command = "google-chrome-stable"
process = "chrome"

# Chrome app - AI window (It will find a window with an active tab with @AI in its title).
[[run_or_raise]]
name = "chromeAI"
class = "google-chrome"
caption = "@AI - Google Chrome$"
command = "google-chrome-stable"
process = "chrome"

# Chrome app - Banks window (It will find a window with an active tab with @Banks in its title).
[[run_or_raise]]
name = "chromeBanks"
class = "google-chrome"
caption = "@Banks - Google Chrome$"
command = "google-chrome-stable"
process = "chrome"

# Chrome app - Misc window (It will find a window with an active tab with no @Cloud|@Banks|@AI|@Mgmt in its title).
[[run_or_raise]]
name = "chromeMisc"
class = "google-chrome"
caption = "^((?!(@Banks|@AI|@Cloud|@Mgmt)).)*$"
command = "google-chrome-stable"
process = "chrome"

# Obsidian app - When raised multiple times it will iterate through opened obsidians.
[[run_or_raise]]
name = "obsidian"
class = "obsidian"
command = "flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@"
process = "obsidian"

# Terminal app (foot) - When raised multiple times it will iterate through opened terminal windows.
[[run_or_raise]]
name = "terminal"
class = "foot"
# Don't want to iterate through terminal windows where nvim or claude code is running.
caption = "^((?!(nvim|claude code)).)*$"
command = "foot"

# Nvim app - When raised multiple times it will iterate through opened nvims.
[[run_or_raise]]
name = "nvim"
# It will find Nvim running inside foot or Konsole (checking for the signature in its title) or as a stand alone app.
caption = "(Nvim|nvim — Konsole)$"
command = "nvim"
process = "nvim$"

# Claude Code app - When raised multiple times it will iterate through opened claude code apps.
[[run_or_raise]]
name = "claude_code"
# Claude Code will run inside of a terminal. It will check the signature in it's title.
caption = "Claude Code$"
command = "foot"
process = "foot"

# File Explorer app (dolphin) - When raised multiple times it will iterate through opened file explorers.
[[run_or_raise]]
name = "fileexplorer"
class = "org.kde.dolphin"
command = "dolphin"
process = "dolphin$"

# KeePassXC app - When raised multiple times it will iterate through opened file explorers.
[[run_or_raise]]
[[run_or_raise]]
name = "keepassxc"
class = "org.keepassxc.KeePassXC"
command = "keepassxc"
process = "keepassxc$"
